### ISSUE TITLE
the drivers fail to build on RH 9.6

### ISSUE THREAD

**Issue by ykulik-rbc** [exablaze-oss/exanic-software#103]
On kernel 5.14.0-570.17.1.el9_6 the driver build fails with the error below. Kernel structure ethtool_ts_info was renamed to kernel_ethtool_ts_info . Changing the structure name fixes the issue.

make[2]: Entering directory '/usr/src/kernels/5.14.0-570.17.1.el9_6.x86_64'
  CC [M]  /data1/home/ykulik/exanic-software-2.7.5/modules/exanic/exanic-main.o
  CC [M]  /data1/home/ykulik/exanic-software-2.7.5/modules/exanic/exanic-filter.o
  CC [M]  /data1/home/ykulik/exanic-software-2.7.5/modules/exanic/exanic-ctx.o
  CC [M]  /data1/home/ykulik/exanic-software-2.7.5/modules/exanic/exanic-dev.o
  CC [M]  /data1/home/ykulik/exanic-software-2.7.5/modules/exanic/exanic-netdev.o
/data1/home/ykulik/exanic-software-2.7.5/modules/exanic/exanic-netdev.c:1668:31: error: initialization of ‘int (*)(struct net_device *, struct kernel_ethtool_ts_info *)’ from incompatible pointer type ‘int (*)(struct net_device *, struct ethtool_ts_info *)’ [-Werror=incompatible-pointer-types]
 1668 |     .get_ts_info            = exanic_netdev_get_ts_info,
      |                               ^~~~~~~~~~~~~~~~~~~~~~~~~
/data1/home/ykulik/exanic-software-2.7.5/modules/exanic/exanic-netdev.c:1668:31: note: (near initialization for ‘exanic_ethtool_ops.get_ts_info’)
cc1: some warnings being treated as errors
make[3]: *** [scripts/Makefile.build:249: /data1/home/ykulik/exanic-software-2.7.5/modules/exanic/exanic-netdev.o] Error 1
make[2]: *** [Makefile:1947: /data1/home/ykulik/exanic-software-2.7.5/modules/exanic] Error 2
make[2]: Leaving directory '/usr/src/kernels/5.14.0-570.17.1.el9_6.x86_64'
make[1]: *** [Makefile:27: default] Error 2
make[1]: Leaving directory '/data1/home/ykulik/exanic-software-2.7.5/modules/exanic'
make: *** [Makefile:9: modules] Error 2

**Comment by AlexeySaff** [comment]
`diff --git a/modules/exanic/Makefile b/modules/exanic/Makefile
index 3a9911e..f5f68e3 100644
--- a/modules/exanic/Makefile
+++ b/modules/exanic/Makefile
@@ -16,8 +16,9 @@ HAS_STRLCPY := ${shell grep -c 'strlcpy'
$(srctree)/include/linux/string.h}
 HAS_FLUSH_WQ_WARN := ${shell grep -c '__warn_flushing_systemwide_wq'
$(srctree)/include/linux/workqueue.h}
 HAS_PTP_CLOCK_ADJFREQ := ${shell grep -c 'adjfreq'
$(srctree)/include/linux/ptp_clock_kernel.h}
 HAS_GFP_TYPES_H := ${shell test -e
$(srctree)/include/linux/gfp_types.h && echo 1 || echo 0}
+HAS_KERNEL_ETHTOOL_TS_INFO := ${shell egrep -c
'kernel_ethtool_ts_info' $(srctree)/include/linux/ethtool.h}

-ccflags-y := -D__HAS_NETDEVICE_DEV_PORT=$(HAS_NETDEVICE_DEV_PORT)
-D__USE_RH_NETDEV_CHANGE_MTU=$(USE_RH_NETDEV_CHANGE_MTU)
-D__RH_ETHTOOL_OPS_EXT=$(RH_ETHTOOL_OPS_EXT)
-D__HAS_KERNEL_ETHTOOL_COALESCE=$(HAS_KERNEL_ETHTOOL_COALESCE_STRUCT)
-D__HAS_KERNEL_NDO_ETH_IOCTL=$(HAS_KERNEL_NDO_ETH_IOCTL)
-D__HAS_NAPI_WEIGHT_PARAM=$(HAS_NAPI_WEIGHT_PARAM)
-D__HAS_NAPI_RESCHEDULE=$(HAS_NAPI_RESCHEDULE)
-D__HAS_PCI_ERR_REPORTING=$(HAS_PCI_ERR_REPORTING)
-D__HAS_STRLCPY=$(HAS_STRLCPY)
-D__HAS_FLUSH_WQ_WARN=$(HAS_FLUSH_WQ_WARN)
-D__HAS_PTP_CLOCK_ADJFREQ=$(HAS_PTP_CLOCK_ADJFREQ)
-D__HAS_GFP_TYPES_H=$(HAS_GFP_TYPES_H) -fstack-protector-strong
-Wformat -Wformat-security
+ccflags-y := -D__HAS_NETDEVICE_DEV_PORT=$(HAS_NETDEVICE_DEV_PORT)
-D__USE_RH_NETDEV_CHANGE_MTU=$(USE_RH_NETDEV_CHANGE_MTU)
-D__RH_ETHTOOL_OPS_EXT=$(RH_ETHTOOL_OPS_EXT)
-D__HAS_KERNEL_ETHTOOL_COALESCE=$(HAS_KERNEL_ETHTOOL_COALESCE_STRUCT)
-D__HAS_KERNEL_NDO_ETH_IOCTL=$(HAS_KERNEL_NDO_ETH_IOCTL)
-D__HAS_NAPI_WEIGHT_PARAM=$(HAS_NAPI_WEIGHT_PARAM)
-D__HAS_NAPI_RESCHEDULE=$(HAS_NAPI_RESCHEDULE)
-D__HAS_PCI_ERR_REPORTING=$(HAS_PCI_ERR_REPORTING)
-D__HAS_STRLCPY=$(HAS_STRLCPY)
-D__HAS_FLUSH_WQ_WARN=$(HAS_FLUSH_WQ_WARN)
-D__HAS_PTP_CLOCK_ADJFREQ=$(HAS_PTP_CLOCK_ADJFREQ)
-D__HAS_GFP_TYPES_H=$(HAS_GFP_TYPES_H)
-D__HAS_KERNEL_ETHTOOL_TS_INFO=$(HAS_KERNEL_ETHTOOL_TS_INFO)
-fstack-protector-strong -Wformat -Wformat-security

 else # normal part makefile

diff --git a/modules/exanic/exanic-netdev.c b/modules/exanic/exanic-netdev.c
index d12cb83..192f63a 100644
--- a/modules/exanic/exanic-netdev.c
+++ b/modules/exanic/exanic-netdev.c
@@ -1517,7 +1517,11 @@ static int exanic_netdev_set_coalesce(struct
net_device *ndev,

 #if defined(ETHTOOL_GET_TS_INFO)
 static int exanic_netdev_get_ts_info(struct net_device *ndev,
+#if __HAS_KERNEL_ETHTOOL_TS_INFO
+                                     struct kernel_ethtool_ts_info *eti)
+#else
                                      struct ethtool_ts_info *eti)
+#endif
 {
 #if defined(CONFIG_PTP_1588_CLOCK) || defined(CONFIG_PTP_1588_CLOCK_MODULE)
     struct exanic_netdev_priv *priv = netdev_priv(ndev);`

**Comment by AlexeySaff** [comment]
yeah, simple is quite simple , but official CISCO position is

"Currently RHEL 9.6 support is targeted for release Q1 CY 2026 per the DE."
